{
 "title": "Basket Items Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "traceId", "label": "Trace ID" }
  ]
 },
 "panels": [
  {
   "title": "Total Exceptions Occured (Metrics)",
   "type": "timeseries",
   "description": "Number of all the exceptions that occured with in the Web Application",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aspnetcore_diagnostics_exceptions_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of updates to basket (Metrics)",
   "type": "timeseries",
   "description": "Rate of basket updates per 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(basket_add_to_basket_count_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of items per minute (Metrics)",
   "type": "timeseries",
   "description": "Rate of items added to basket per 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(basket_add_to_basket_items_added_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate in Basket Service",
   "type": "timeseries",
   "description": "Rate of the number of errors that occur when adding a new item to the basket",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(basket_add_to_basket_errors_count_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Selected trace: ${traceId}",
   "type": "traces",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "query": "${traceId}" }
   ]
  },
  {
   "title": "All the Success Traces in WebApp",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "service": "WebApp", "tags": "http.response.status_code=200" }
   ]
  },
  {
   "title": "All the Success Traces in BasketService",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "service": "BasketService", "tags": "http.response.status_code=200" }
   ]
  }
 ]
}